Adding build rules to install local version of PYB11Generator.

diff --git a/src/thirdPartyLibs/makefile.in b/src/thirdPartyLibs/makefile.in
--- a/src/thirdPartyLibs/makefile.in
+++ b/src/thirdPartyLibs/makefile.in
@@ -59,6 +59,10 @@ PYBIND11URL = https://github.com/pybind/pybind11/archive/v2.2.1.tar.gz
 PYBIND11DIR = $(PYBIND11DIST:.tar.gz=)
 PYBIND11BUILDDATE = $(patsubst %.tar.gz, .%.date, $(PYBIND11DIST))
 
+# PYB11Generator
+PYB11GENDIR = $(srcdir)/PYB11Generator
+PYB11GENBUILDDATE = .PYB11Generator.date
+
 # PyGnuplot
 GNUPLOTDIST = gnuplot-py-1.8.tar.gz
 GNUPLOTURL = http://downloads.sourceforge.net/gnuplot-py/gnuplot-py-1.8.tar.gz?modtime=1209767882&big_mirror=0
@@ -323,6 +327,7 @@ $(PYBINDGENPATCHDATE):	$(PYBINDGENBUILDDATE)
 #-------------------------------------------------------------------------------
 all:	$(PYTHONTARGET) \
 	$(PYBINDGENPATCHDATE) \
+	$(PYB11GENBUILDDATE) \
 	$(PETSCTARGETS) \
 	$(ATSBUILDDATE) \
 	$(OPENSUBDIVTARGETS) \
@@ -419,6 +424,22 @@ $(PIPEXE):	$(PYTHONTARGET) cache/$(PIPDIST)
 	echo "ERROR building PIP."; \
 	exit 1; \
 	fi
+
+#-------------------------------------------------------------------------------
+# PYB11Generator
+#-------------------------------------------------------------------------------
+$(PYB11GENBUILDDATE):	$(PYTHONTARGET) $(PYB11GENDIR)/PYB11Generator/__init__.py
+	@echo "################################################################################"
+	@echo "# Building PYB11Generator"
+	@echo "################################################################################"
+	@$(MKDIR) $(LIBDIR) $(prefix)/include $(prefix)/bin
+	$(SHELL) -ec 'cd $(PYB11GENDIR); $(PYTHONEXE) setup.py install --prefix $(prefix);'
+	@if test -n "`$(PYTHONEXE) -c 'import PYB11Generator'`"; then \
+	echo "ERROR building PYB11Generator python extension."; \
+	rm -f $(PYB11GENBUILDDATE); \
+	exit 1; \
+	fi
+	touch $(PYB11GENBUILDDATE)
 
 #-------------------------------------------------------------------------------
 # Gnuplot python extension
