Interim checkin working on PIP for third party libs.

diff --git a/src/thirdPartyLibs/makefile.in b/src/thirdPartyLibs/makefile.in
--- a/src/thirdPartyLibs/makefile.in
+++ b/src/thirdPartyLibs/makefile.in
@@ -35,18 +35,21 @@ PYTHONDIR = $(PYTHONDIST:.tgz=)
 PYTHONBUILDDATE = $(patsubst %.tgz, .%.date, $(PYTHONDIST))
 PYTHONTARGET = @PYTHONTARGET@
 
+# PIP
+PIPDIST = pip-9.0.1-py2.py3-none-any.whl 
+SETUPTOOLSDIST = setuptools-38.4.0-py2.py3-none-any.whl
+WHEELDIST = wheel-0.30.0-py2.py3-none-any.whl
+PIPURL = https://pypi.python.org/packages/b6/ac/7015eb97dc749283ffdec1c3a88ddb8ae03b8fad0f0e611408f196358da3/pip-9.0.1-py2.py3-none-any.whl#md5=297dbd16ef53bcef0447d245815f5144
+SETUPTOOLSURL = https://pypi.python.org/packages/75/d1/5abca4ccf61a7ab86c255dd315fb96e566fbf9b5d3a480e72c93e8ec2802/setuptools-38.4.0-py2.py3-none-any.whl#md5=a5c6620a59f19f2d5d32bdca18c7b47e
+WHEELURL = https://pypi.python.org/packages/0c/80/16a85b47702a1f47a63c104c91abdd0a6704ee8ae3b4ce4afc49bc39f9d9/wheel-0.30.0-py2.py3-none-any.whl#md5=1d61793f816d6b60513364fe2de9c1b3
+PIPEXE = $(PREFIX)/bin/pip
+
 # BASKET
 BASKETDIST = Basket-1.0.tar.gz
 BASKETURL = https://github.com/dbaty/Basket/archive/1.0.tar.gz
 BASKETDIR = $(subst .tar.gz,,$(BASKETDIST))
 BASKETEXE = $(prefix)/bin/basket
 BASKETROOT = BASKET
-BASKETPKGS = pip setuptools wheel numpy
-
-# PIP
-PIPBUILDDATE = .pip.date
-PIPEXE = $(PREFIX)/bin/pip
-PIPDISTS = pip setuptools wheel
 
 # Numpy
 NUMPYBUILDDATE = .numpy.date
@@ -102,24 +105,6 @@ TAUURL=http://www.cs.uoregon.edu/Research/tau/tau_releases/$(TAUDIST)
 TAUDIR = $(TAUDIST:.tar.gz=)
 TAUBUILDDATE = $(patsubst %.tar.gz, .%.date, $(TAUDIST))
 TAUDUMMYDATE = $(patsubst %.tar.gz, .%.dummydate, $(TAUDIST))
-
-# Pygtk
-PYGTKDIST = pygtk-2.12.1.tar.gz
-PYGTKURL = http://saimei.acc.umu.se/pub/GNOME/sources/pygtk/2.12/$(PYGTKDIST)
-PYGTKDIR = $(PYGTKDIST:.tar.gz=)
-PYGTKBUILDDATE = $(patsubst %.tar.gz, .%.date, $(PYGTKDIST))
-
-# Matplotlib
-MATPLOTLIBDIST = matplotlib-1.3.1.tar.gz
-MATPLOTLIBURL = http://sourceforge.net/projects/matplotlib/files/matplotlib/matplotlib-1.3.1/matplotlib-1.3.1.tar.gz/download
-MATPLOTLIBDIR = $(MATPLOTLIBDIST:.tar.gz=)
-MATPLOTLIBBUILDDATE = $(patsubst %.tar.gz, .%.date, $(MATPLOTLIBDIST))
-
-# Scipy
-SCIPYDIST = scipy-0.13.2.tar.gz
-SCIPYURL = http://sourceforge.net/projects/scipy/files/scipy/0.13.2/$(SCIPYDIST)/download
-SCIPYDIR = $(SCIPYDIST:.tar.gz=)
-SCIPYBUILDDATE = $(patsubst %.tar.gz, .%.date, $(SCIPYDIST))
 
 # F2PY
 # F2PYDIST = F2PY-2.45.241_1926.tar.gz
@@ -204,12 +189,6 @@ PILURL = http://effbot.org/downloads/$(PILDIST)
 PILDIR = $(PILDIST:.tar.gz=)
 PILBUILDDATE = $(patsubst %.tar.gz, .%.date, $(PILDIST))
 
-# pybindgen
-PYBINDGENDIST = PyBindGen-0.17.0.tar.gz
-PYBINDGENURL = https://pypi.python.org/packages/source/P/PyBindGen/$(PYBINDGENDIST)
-PYBINDGENDIR = $(PYBINDGENDIST:.tar.gz=)
-PYBINDGENBUILDDATE = $(patsubst %.tar.gz, .%.date, $(PYBINDGENDIST))
-
 # WildMagic
 WILDMAGICDIST = WildMagic5p9.zip
 WILDMAGICURL = http://sourceforge.net/projects/spheral/files/ThirdPartySources/$(WILDMAGICDIST)/download
@@ -222,12 +201,6 @@ QHULLURL = http://www.qhull.org/download/$(QHULLDIST)
 QHULLDIR = qhull-2015.2
 QHULLINCDIR = $(prefix)/include/qhull
 QHULLDATE = $(patsubst %.tgz, .%.date, $(QHULLDIST))
-
-# mpi4py
-MPI4PYDIST = mpi4py-2.0.0.tar.gz
-MPI4PYURL = https://bitbucket.org/mpi4py/mpi4py/downloads/$(MPI4PYDIST)
-MPI4PYDIR = $(MPI4PYDIST:.tar.gz=)
-MPI4PYBUILDDATE = $(patsubst %.tar.gz, .%.date, $(MPI4PYDIST))
 
 # HDF5
 HDF5DIST = hdf5-1.8.19.tar.bz2
@@ -327,12 +300,6 @@ R3DDIR = r3d-master
 R3DBUILDDATE = $(patsubst %.zip, .%.date, $(R3DDIST))
 R3DINCDIR = $(prefix)/include/r3d
 
-# Python Sobol sequence
-PYSOBOLDIST = sobol_dev.zip
-PYSOBOLURL = https://github.com/crankycoder/sobol_seq/archive/dev.zip
-PYSOBOLDIR = c/sobol_seq-dev
-PYSOBOLBUILDDATE = $(patsubst %.zip, .%.date, $(PYSOBOLDIST))
-
 # pybind11
 PYBIND11DIST = pybind11-2.0.1.tar.gz
 PYBIND11URL = https://github.com/pybind/pybind11/archive/v2.0.1.tar.gz
@@ -347,13 +314,11 @@ EASYPROFILEBUILDDATE = $(patsubst %.tar.gz, .%.date, $(EASYPROFILEDIST))
 
 #-------------------------------------------------------------------------------
 all:	$(PYTHONTARGET) \
+	$(BASKETROOT) \
 	$(GCCXMLTARGETS) \
-	$(MATPLOTLIBTARGETS) \
-	$(SCIPYTARGETS) \
 	$(PETSCTARGETS) \
 	$(ATSBUILDDATE) \
 	$(ZLIBBUILDDATE) \
-	$(PYBINDGENBUILDDATE) \
 	$(OPENSUBDIVTARGETS) \
 	$(EXTRATHIRDPARTYTARGETS) \
 #	$(HYPREBUILDDATE)
@@ -362,19 +327,15 @@ all:	$(PYTHONTARGET) \
 
 clean:
 	rm -fr $(PYTHONDIR) $(PYTHONBUILDDATE) \
-	       $(NUMPYDIR) $(NUMPYBUILDDATE) \
 	       $(GNUPLOTDIR) $(GNUPLOTBUILDDATE) \
 	       $(PSYCODIR) $(PSYCOBUILDDATE) \
 	       $(BOOSTDIR) $(BOOSTDATE) \
                $(CMAKEDIR) \
                $(GCCXMLDIR) $(GCCXMLDATE) \
 	       $(PSYCODIR) \
-	       $(MPI4PYDIR) $(MPI4PYBUILDDATE) \
                $(PARMETISDIR) $(PARMETISBUILDDATE) \
-	       $(SCIPYDIR) $(SCIPYBUILDDATE) \
 	       $(GSLDIR) \
 	       $(PYGSLDIR) \
-               $(MATPLOTLIBDIR) $(MATPLOTLIBBUILDDATE) \
 	       $(HASHMAPDATE) \
 	       $(VISITWRITERDIR) $(VISITWRITERBUILDDATE) \
 	       $(ATSWRITERDIR) $(ATSWRITERBUILDDATE) \
@@ -382,7 +343,6 @@ clean:
 	       $(FFTWPPDIR) $(FFTWPPBUILDDATE) \
 	       $(ARRAYDIR) $(ARRAYBUILDDATE) \
 	       $(ZLIBDIR) $(ZLIBBUILDDATE) \
-	       $(PYBINDGENDIR) $(PYBINDGENBUILDDATE) \
 	       $(QHULLDIR) $(QHULLDATE) \
 	       $(HDF5DIR) $(HDF5BUILDDATE) \
 	       $(SILODIR) $(SILOBUILDDATE) \
@@ -431,16 +391,36 @@ $(PYTHONBUILDDATE):	$(PYTHON) $(PYTHONDIST) $(ZLIBBUILDDATE)
 	touch $(PYTHONBUILDDATE)
 
 #-------------------------------------------------------------------------------
+# PIP
+#-------------------------------------------------------------------------------
+$(PIPDIST):
+	$(CURL) "$(PIPURL)" > $(PIPDIST)
+	$(CURL) "$(SETUPTOOLSURL)" > $(SETUPTOOLSDIST)
+	$(CURL) "$(WHEELURL)" > $(WHEELDIST)
+
+$(PIPEXE):	$(PYTHONTARGET) $(PIPDIST)
+	@echo "################################################################################"
+	@echo "# Building PIP"
+	@echo "################################################################################"
+	#$(PYTHONEXE) -m ensurepip --default-pip # --no-index --find-links $(BASKETROOT)
+	$(PYTHONEXE) $(patsubst %,%/pip,$(PIPDIST)) install --no-index $(PIPDIST)
+	$(PYTHONEXE) -m pip install --upgrade setuptools wheel --no-index --find-links .
+	@if test -n "`$(PYTHONEXE) -c 'import pip'`" -a \
+	         -e $(PIPEXE); then \
+	echo "ERROR building PIP."; \
+	exit 1; \
+	fi
+
+#-------------------------------------------------------------------------------
 # Basket
 #-------------------------------------------------------------------------------
 $(BASKETDIST):
 	$(CURL) "$(BASKETURL)" > $(BASKETDIST)
 
-$(BASKETEXE):	$(BASKETDIST) $(PYTHONBUILDDATE)
+$(BASKETEXE):	$(BASKETDIST) $(PYTHONTARGET) $(PIPEXE)
 	@echo "################################################################################"
 	@echo "# Building $(BASKETDIST)"
 	@echo "################################################################################"
-	$(PYTHONEXE) -m ensurepip --default-pip # --no-index --find-links $(BASKETROOT)
 	@$(MKDIR) $(LIBDIR) $(prefix)/bin
 	rm -fr $(BASKETDIR)
 	$(GZIP) -dc $(BASKETDIST) | $(TAR) -xf -
@@ -457,37 +437,23 @@ $(BASKETEXE):	$(BASKETDIST) $(PYTHONBUILDDATE)
 
 $(BASKETROOT):	$(BASKETEXE)
 	env BASKET_ROOT=$(BASKETROOT) $(BASKETEXE) init
-	env BASKET_ROOT=$(BASKETROOT) $(BASKETEXE) download $(BASKETPKGS)
+	env BASKET_ROOT=$(BASKETROOT) $(BASKETEXE) download $(PIPTARGETS)
+	$(PYTHONEXE) -m pip install --upgrade $(PIPTARGETS) --no-index --find-links $(BASKETROOT)
 
-#-------------------------------------------------------------------------------
-# PIP
-#-------------------------------------------------------------------------------
-$(PIPBUILDDATE):	$(PYTHONTARGET) $(BASKETROOT)
-	@echo "################################################################################"
-	@echo "# Building PIP"
-	@echo "################################################################################"
-	$(PYTHONEXE) -m pip install --upgrade pip setuptools wheel --no-index --find-links $(BASKETROOT)
-	@if test -n "`$(PYTHONEXE) -c 'import pip'`"; then \
-	echo "ERROR building python PIP installer."; \
-	rm -f $(PIPBUILDDATE); \
-	exit 1; \
-	fi
-	touch $(PIPBUILDDATE)
-
-#-------------------------------------------------------------------------------
-# Numpy python extension
-#-------------------------------------------------------------------------------
-$(NUMPYBUILDDATE):	$(PYTHONTARGET) $(BASKETROOT)
-	@echo "################################################################################"
-	@echo "# Building Numpy"
-	@echo "################################################################################"
-	$(PYTHONEXE) -m pip install --upgrade numpy --no-index --find-links $(BASKETROOT)
-	@if test -n "`$(PYTHONEXE) -c 'import numpy'`"; then \
-	echo "ERROR building numpy."; \
-	rm -f $(NUMPYBUILDDATE); \
-	exit 1; \
-	fi
-	touch $(NUMPYBUILDDATE)
+# #-------------------------------------------------------------------------------
+# # Numpy python extension
+# #-------------------------------------------------------------------------------
+# $(NUMPYBUILDDATE):	$(PYTHONTARGET) $(BASKETROOT)
+# 	@echo "################################################################################"
+# 	@echo "# Building Numpy"
+# 	@echo "################################################################################"
+# 	$(PYTHONEXE) -m pip install --upgrade numpy --no-index --find-links $(BASKETROOT)
+# 	@if test -n "`$(PYTHONEXE) -c 'import numpy'`"; then \
+# 	echo "ERROR building numpy."; \
+# 	rm -f $(NUMPYBUILDDATE); \
+# 	exit 1; \
+# 	fi
+# 	touch $(NUMPYBUILDDATE)
 
 # $(NUMPYDIST):
 # 	$(CURL) "$(NUMPYURL)" > $(NUMPYDIST)
@@ -517,7 +483,7 @@ $(NUMPYBUILDDATE):	$(PYTHONTARGET) $(BASKETROOT)
 $(GNUPLOTDIST):
 	$(CURL) "$(GNUPLOTURL)" > $(GNUPLOTDIST)
 
-$(GNUPLOTBUILDDATE):	$(PYTHONTARGET) $(NUMPYBUILDDATE) $(GNUPLOTDIST)
+$(GNUPLOTBUILDDATE):	$(PYTHONTARGET) $(BASKETROOT) $(GNUPLOTDIST)
 	@echo "################################################################################"
 	@echo "# Building $(GNUPLOTDIST)"
 	@echo "################################################################################"
@@ -720,83 +686,9 @@ $(TAUDUMMYDATE):  $(TAUDIST)
 	touch $(TAUDUMMYDATE)
 
 #-------------------------------------------------------------------------------
-# PyGTK
-#-------------------------------------------------------------------------------
-$(PYGTKDIST):
-	$(CURL) "$(PYGTKURL)" > $(PYGTKDIST)
-
-$(PYGTKBUILDDATE):  $(NUMPYBUILDDATE) $(PYGTKDIST)
-	@echo "################################################################################"
-	@echo "# Building $(PYGTKDIST)"
-	@echo "################################################################################"
-	@$(MKDIR) $(LIBDIR) $(prefix)/include $(prefix)/bin
-	rm -fr $(PYGTKDIR) $(PYGTKDUMMYDATE)
-	$(GZIP) -dc $(PYGTKDIST) | $(TAR) -xf -
-	$(SHELL) -ec "cd $(PYGTKDIR); \
-	env CC='$(PYTHONCC)' CXX='$(PYTHONCXX)' PYTHON=$(PYTHONEXE) ./configure --enable-thread --prefix=$(prefix); \
-	$(MAKE); \
-	$(MAKE) install"
-	@if test -n "`$(PYTHONEXE) -c 'import pygtk'`"; then \
-	echo "ERROR building PyGTK extension."; \
-	rm -f $(PYGTKBUILDDATE); \
-	exit 1; \
-	fi
-	rm -fr $(PYGTKDIR)
-	touch $(PYGTKBUILDDATE)
-
-#-------------------------------------------------------------------------------
-# matplotlib
-#-------------------------------------------------------------------------------
-$(MATPLOTLIBDIST):
-	$(CURL) "$(MATPLOTLIBURL)" > $(MATPLOTLIBDIST)
-
-$(MATPLOTLIBBUILDDATE): $(MATPLOTLIBDIST)
-	@echo "################################################################################"
-	@echo "# Building $(MATPLOTLIBDIST)"
-	@echo "################################################################################"
-	@$(MKDIR) $(LIBDIR) $(prefix)/include $(prefix)/bin
-	rm -fr $(MATPLOTLIBDIR) $(MATPLOTLIBDUMMYDATE)
-	$(GZIP) -dc $(MATPLOTLIBDIST) | $(TAR) -xf -
-	$(SHELL) -ec "cd $(MATPLOTLIBDIR); \
-	env PKG_CONFIG_PATH=$(prefix)/lib/pkgconfig $(PYTHONEXE) setup.py build --prefix $(prefix); \
-	$(PYTHONEXE) setup.py install --prefix $(prefix)"
-	@if test -n "`$(PYTHONEXE) -c 'import matplotlib'`"; then \
-	echo "ERROR building matplotlib extension."; \
-	rm -f $(MATPLOTLIBBUILDDATE); \
-	exit 1; \
-	fi
-	rm -fr $(MATPLOTLIBDIR)
-	touch $(MATPLOTLIBBUILDDATE)
-
-#-------------------------------------------------------------------------------
-# SciPy
-#-------------------------------------------------------------------------------
-$(SCIPYDIST):
-	$(CURL) "$(SCIPYURL)" > $(SCIPYDIST)
-
-$(SCIPYBUILDDATE):  $(PYTHONTARGET) $(NUMPYBUILDDATE) $(SCIPYDIST)
-	@echo "################################################################################"
-	@echo "# Building $(SCIPYDIST)"
-	@echo "################################################################################"
-	@$(MKDIR) $(LIBDIR) $(prefix)/include $(prefix)/bin
-	rm -fr $(SCIPYDIR) $(SCIPYDUMMYDATE)
-	$(GZIP) -dc $(SCIPYDIST) | $(TAR) -xf -
-#	$(PATCH) $(SCIPYDIR)/setup.py $(srcdir)/$(SCIPYDIR)-setup.py-patch 
-	$(SHELL) -ec "cd $(SCIPYDIR); \
-	env PKG_CONFIG_PATH=$(prefix)/lib/pkgconfig $(PYTHONEXE) setup.py build; \
-	$(PYTHONEXE) setup.py install --prefix $(prefix)"
-	@if test -n "`$(PYTHONEXE) -c 'import scipy'`"; then \
-	echo "ERROR building scipy extension."; \
-	rm -f $(SCIPYBUILDDATE); \
-	exit 1; \
-	fi
-	rm -fr $(SCIPYDIR)
-	touch $(SCIPYBUILDDATE)
-
-#-------------------------------------------------------------------------------
 # F2Py -- Needed by SciPy.
 #-------------------------------------------------------------------------------
-# $(F2PYBUILDDATE):  $(F2PYDIST) $(PYTHONTARGET) $(NUMPYBUILDDATE) 
+# $(F2PYBUILDDATE):  $(F2PYDIST) $(PYTHONTARGET) $(BASKETROOT) 
 # 	@echo "################################################################################"
 # 	@echo "# Building $(F2PYDIST)"
 # 	@echo "################################################################################"
@@ -1216,28 +1108,6 @@ $(QHULLDATE):	$(PYTHONTARGET) $(QHULLDIST) $(CMAKEEXE)
 	touch $(QHULLDATE)
 
 #-------------------------------------------------------------------------------
-# mpi4py
-#-------------------------------------------------------------------------------
-$(MPI4PYDIST):
-	$(CURL) "$(MPI4PYURL)" > $(MPI4PYDIST)
-
-$(MPI4PYBUILDDATE):  $(PYTHONTARGET) $(MPI4PYDIST)
-	@echo "################################################################################"
-	@echo "# Building $(MPI4PYDIST)"
-	@echo "################################################################################"
-	rm -fr $(MPI4PYDIR)
-	$(GZIP) -dc $(MPI4PYDIST) | $(TAR) -xf -
-	#$(PATCH) $(MPI4PYDIR)/setup.cfg $(srcdir)/mpi4py-1.2.2_setup_dot_cfg.patch
-	env MPICC='$(MPI4PYCC) $(MPICCFLAGS)' $(SHELL) -ec "cd $(MPI4PYDIR); $(PYTHONEXE) setup.py install --prefix $(prefix)"
-	@if test -n "`$(PYTHONEXE) -c 'from mpi4py import MPI'`"; then \
-	echo "ERROR building mpi4py python extension."; \
-	rm -f $(MPI4PYBUILDDATE); \
-	exit 1; \
-	fi
-	rm -fr $(MPI4PYDIR)
-	touch $(MPI4PYBUILDDATE)
-
-#-------------------------------------------------------------------------------
 # HDF5
 #-------------------------------------------------------------------------------
 $(HDF5DIST):
@@ -1622,7 +1492,7 @@ $(R3DBUILDDATE):	$(R3DDIST)
 $(PYSOBOLDIST):
 	$(CURL) "$(PYSOBOLURL)" > $(PYSOBOLDIST)
 
-$(PYSOBOLBUILDDATE):	$(PYTHONTARGET) $(NUMPYBUILDDATE) $(PYSOBOLDIST)
+$(PYSOBOLBUILDDATE):	$(PYTHONTARGET) $(BASKETROOT) $(PYSOBOLDIST)
 	@echo "################################################################################"
 	@echo "# Building $(PYSOBOLDIST)"
 	@echo "################################################################################"
